""""""""""""""""""""
"""NORMAL SETTING"""
"""""""""""""""""""" 
syntax on
filetype on
set nocompatible
set ignorecase smartcase
set nowrapscan  "turn off search wrapping
set incsearch 
set nu
set showcmd
set hls
set title
set ru
set sc
set bs=indent,eol,start
set sm
set ci
set ai
set si
set paste
set sw=4
set ts=4
set diffopt+=iwhite
set history=1000
set vb t_vb=
set et
"set cursorline
set cursorcolumn

set fenc=utf-8
set fencs=utf-8,cp949,unicode

set fileencoding=korea
set encoding=korea
set km=startsel,stopsel

set nobackup
set nowritebackup
set selectmode=mouse
set autowrite

set t_ti= t_te=
set foldmethod=marker
"set gfn=Bitstream\ Vera\ Sans\ Mono:h10
"set gfn=D2Coding\ Regular\ 12
"set guifont=D2Coding:h11
set guifont=D2Coding:h12

" ,t Toggle Taglist
map ,t :TlistToggle<CR>
map ,h :Header<CR>
map ,s :Commenter<CR>
map ,S :CommenterS<CR>
map ,va :!vauto %<CR>
map ,vd :!vdel %<CR>

map ,0  a({@"vl-width"{1'b0}}),<ESC>
map ,1  a({@"vl-width"{1'b1}}),<ESC>
map ,`  a(_NC_@"vl-cell-name"_@"vl-name"[]),<ESC>

set isfname-=, "for ncverilog log
set isfname-=+ "for ncverilog incdir/define
set isfname-== "for bash/csh script

""""""""""""""""""""""""
"""BACKGROUND SETTING"""
""""""""""""""""""""""""
"source ~/.vimcolor
hi clear
set bg=dark
if exists("syntax_on")
   syntax reset
endif

" ctermfg => light or normal is thick, dark is thin
"					FONT				FONT BG				FONT COLOR
hi	Normal			term=none			ctermbg=black		ctermfg=lightgrey						guifg=white			guibg=black
hi	Comment			term=none								ctermfg=darkcyan						guifg=#99ffff
hi	Constant		term=underline							ctermfg=lightgrey						guifg=#ff99ff							gui=none
hi	Identifier		term=underline							ctermfg=lightcyan						guifg=#99ffff
hi	Ignore													ctermfg=black      						guifg=#000000
hi	PreProc			term=underline							ctermfg=darkgreen						guifg=#9999ff
hi	Search			term=none			ctermbg=red			ctermfg=black							guifg=black			guibg=#999933
hi	Special			term=none								ctermfg=darkgreen						guifg=#ff9999
hi	Statement		term=none								ctermfg=darkyellow						guifg=#ffff99							gui=none
hi	Type			term=underline							ctermfg=darkred							guifg=#99ff99							gui=none
hi	Error			term=reverse		ctermbg=lightred	ctermfg=white							guifg=#ffffff		guibg=#ff9999
hi	Todo			term=standout		ctermbg=darkyellow	ctermfg=black							guifg=#000000		guibg=#999933

" From the source:
hi	Cursor																							guifg=white		    guibg=black
hi	iCursor																							guifg=white		    guibg=steelblue
hi	Directory		term=bold								ctermfg=darkcyan						guifg=#99ffff
hi	ErrorMsg		term=standout		ctermbg=darkred		ctermfg=white							guifg=white			guibg=#ff9999
hi	IncSearch		term=reverse													cterm=reverse											gui=reverse
hi	LineNr			term=underline							ctermfg=yellow							guifg=#ffff99
hi	ModeMsg			term=bold														cterm=bold												gui=bold
hi	MoreMsg			term=bold								ctermfg=darkgreen						guifg=#99ff99							gui=bold
hi	NonText			term=bold								ctermfg=blue							guifg=#666666							gui=bold
hi	Question		term=standout							ctermfg=darkgreen						guifg=#99ff99							gui=bold
hi	SpecialKey		term=bold								ctermfg=darkblue						guifg=#666666
hi	StatusLine		term=reverse,bold												cterm=reverse	guifg=white			guibg=darkblue		gui=reverse
hi	StatusLineNC	term=reverse													cterm=reverse	guifg=white			guibg=#333333		gui=reverse
hi	Title			term=bold								ctermfg=darkmagenta						guifg=#ff99ff							gui=bold
hi	WarningMsg		term=standout							ctermfg=red								guifg=#ff9999
hi	Visual			term=reverse													cterm=reverse	guifg=white			guibg=darkgreen		gui=reverse
hi	vertSplit																																gui=reverse
hi	VisualNOS																																gui=underline
hi	WildMenu																						guifg=#000000		guibg=#999933
hi	Folded																							guifg=#99ffff		guibg=#666666
hi	FoldColumn																						guifg=#99ffff		guibg=#666666
hi	DiffAdd																												guibg=#9999fF
hi	DiffChange																											guibg=#ff99fF
hi	DiffDelete		term=none																		guifg=#ff9999		guibg=#9999fF
hi	DiffText		term=reverse																						guibg=#ff9999
hi	Underlined		term=underline																	guifg=#9999ff							gui=underline

""""""""""""""""""""""""
""""GUI MODE SETTING""""
""""""""""""""""""""""""
if has("gui_running")

	set nocompatible
	"filetype plugin on
	filetype plugin indent on

    set cursorline
    set cursorcolumn

	au GUIEnter * winsize 150 40
	"au GUIEnter * winpos  3840 25

	"let loaded_explorer=1
	"let g:explVertical=1
	"let g:explSplitBelow=1
	let g:explSplitRight=1
	let g:explStartRight=0
	let g:explStartBelow=0
	"let g:explWinSize=""
	"let g:explDetailedList=1

	"set guifont=Bitstream\ Vera\ Sans\ Mono\ Bold\ 8
	"set guifont=Bitstream\ Vera\ Sans\ Mono\ 8
	"set guifont=Bitstream\ Vera\ Sans\ Mono\ 9
	"set guifont=DejaVu\ Sans\ Mono\ Book\ 9
    "set gfn=D2Coding\ Regular\ 9
    "set gfn=D2Coding\ Regular\ 10
    "set gfn=D2Coding\ Regular\ 11
	"set guifont=Bitstream\ Vera\ Sans\ Mono\ 11
	"set guifont=Bitstream\ Vera\ Sans\ Mono\ Bold\ 9
	"set lines=50
	"set columns=150
	set guitablabel=[%N]\ %t\ %M

	""""""""""""""""""""""""
	"""BACKGROUND SETTING"""
	""""""""""""""""""""""""
	colorscheme torte
	" ctermfg => light or normal is thick, dark is thin
	"					FONT				FONT BG				FONT COLOR
	hi	Normal			term=none			ctermbg=black		ctermfg=white							guifg=#FFFFFF		guibg=black
	hi	Comment			term=none								ctermfg=darkgreen						guifg=#48d1cc
	"hi	Constant		term=underline							ctermfg=lightgrey						guifg=#ff99ff							gui=none
	"hi	Identifier		term=underline							ctermfg=lightcyan						guifg=#99ffff
	"hi	Ignore													ctermfg=black      						guifg=#000000
	"hi	PreProc			term=underline							ctermfg=darkgreen						guifg=#9999ff
	"hi	Search			term=none			ctermbg=red			ctermfg=black							guifg=black			guibg=#999933
	"hi	Special			term=none								ctermfg=darkgreen						guifg=#ff9999
	hi	Statement		term=none								ctermfg=darkgreen						guifg=#ffff55							gui=none
	"hi	Type			term=underline							ctermfg=darkred							guifg=#99ff99							gui=none
	"hi	Error			term=reverse		ctermbg=lightred	ctermfg=white							guifg=#ffffff		guibg=#ff9999
	"hi	Todo			term=standout		ctermbg=darkyellow	ctermfg=black							guifg=#000000		guibg=#999933
	
	" From the source:
    "hi	Cursor																							guifg=white		guibg=black
    hi	Cursor																							guifg=black		guibg=white
    hi	iCursor																							guifg=white		    guibg=steelblue
	"hi	Directory		term=bold								ctermfg=darkcyan						guifg=#99ffff
	"hi	ErrorMsg		term=standout		ctermbg=darkred		ctermfg=white							guifg=white			guibg=#ff9999
	"hi	IncSearch		term=reverse													cterm=reverse											gui=reverse
	hi	LineNr			term=underline							ctermfg=darkyellow							guifg=#ffff00
	"hi	ModeMsg			term=bold														cterm=bold												gui=bold
	"hi	MoreMsg			term=bold								ctermfg=darkgreen						guifg=#99ff99							gui=bold
	"hi	NonText			term=bold								ctermfg=blue							guifg=#666666							gui=bold
	"hi	Question		term=standout							ctermfg=darkgreen						guifg=#99ff99							gui=bold
	"hi	SpecialKey		term=bold								ctermfg=darkblue						guifg=#666666
	"hi	StatusLine		term=reverse,bold												cterm=reverse	guifg=white			guibg=darkblue		gui=reverse
	"hi	StatusLineNC	term=reverse													cterm=reverse	guifg=white			guibg=#333333		gui=reverse
	"hi	Title			term=bold								ctermfg=darkmagenta						guifg=#ff99ff							gui=bold
	"hi	WarningMsg		term=standout							ctermfg=red								guifg=#ff9999
	"hi	Visual			term=reverse													cterm=reverse	guifg=white			guibg=darkgreen		gui=reverse
	"hi	vertSplit																																gui=reverse
	"hi	VisualNOS																																gui=underline
	"hi	WildMenu																						guifg=#000000		guibg=#999933
	"hi	Folded																							guifg=#99ffff		guibg=#666666
	"hi	FoldColumn																						guifg=#99ffff		guibg=#666666
	"hi	DiffAdd																												guibg=#9999fF
	"hi	DiffChange																											guibg=#ff99fF
	"hi	DiffDelete		term=none																		guifg=#ff9999		guibg=#9999fF
	"hi	DiffText		term=reverse																						guibg=#ff9999
	"hi	Underlined		term=underline																	guifg=#9999ff							gui=underline

endif

function! Incr()
    let a = line('.') - line("'<")
    let c = virtcol("'<")
    if a > 0
        execute 'normal! '.c.'|'.a."\<C-a>"
    endif
    normal `<
endfunction
vnoremap <C-a> :call Incr()<CR>

function! Decr()
    let a = line('.') - line("'<")
    let c = virtcol("'<")
    if a > 0
        execute 'normal! '.c.'|'.a."\<C-x>"
    endif
    normal `<
endfunction
vnoremap <C-x> :call Decr()<CR>
